name: Docker Action

on: push

jobs:
  docker-steps: 
    runs-on: ubuntu-latest
    container: 
      image: node:latest
    steps: 
      - name: step with docker
        uses: docker://node:16.16.0-alpine3.16
        with:  
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v3
      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "hello slack"
      # - name: step with script
      #   uses: docker://node:16.16.0-alpine3.16
      #   with:  
      #     entrypoint: ./script.sh
      #     args: "string"

      