name: Matrix

on: push

jobs:
  node-versions:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        # windows-latest
        node_version: [6, 8, 10]
        # for adding extra vars for appropriate context
        include:
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true"
        exclude:
          - os: macos-latest
            node_version: 6
      # fail-fast: true
      # max-parallel: 2
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{matrix.is_ubuntu_8}}
    steps:
      - name: Log node version
        run: node -v
      # - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      # - run: npm ci
      # - run: npm test
      - name: Log another node version
        run: |
          node -v
          echo $IS_UBUNTU_8
