name: Matrix

on: push

jobs:
  node-versions:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
      # fail-fast: true
      # max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      # - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      # - run: npm ci
      # - run: npm test
      - name: Log another node version
        run: node -v
